FROM python:3.10

# 1. Install system dependencies + Cron
RUN apt-get update && apt-get install -y \
    ffmpeg \
    cron \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 2. Install Python Dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# 3. Copy Project Files
COPY . .

# 4. Setup Cron
# Copy the crontab file to the cron.d directory
COPY crontab /etc/cron.d/django-cron
# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/django-cron
# Apply cron job
RUN crontab /etc/cron.d/django-cron
# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# 5. Create directories
RUN mkdir -p /app/downloads /app/static /app/media

# 6. Copy and permission the Entrypoint
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# 7. Start via the Entrypoint script
ENTRYPOINT ["sh", "/app/entrypoint.sh"]
