FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# 2. System Deps: Cleanup ensures the layer remains small
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    libavfilter-extra \
    cron \
    && rm -rf /var/lib/apt/lists/*

# 3. Python Deps: Install before code to cache this heavy layer
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copy Project Files
# This puts EVERYTHING (including crontab and entrypoint.sh) into /app
COPY . .

# 5. Setup Cron & Directories & Permissions (Combined for Speed)
# We move files that are already in /app instead of COPYing them again.
RUN mv crontab /etc/cron.d/django-cron && \
    chmod 0644 /etc/cron.d/django-cron && \
    crontab /etc/cron.d/django-cron && \
    touch /var/log/cron.log && \
    mkdir -p /app/downloads /app/static /app/media && \
    chmod +x /app/entrypoint.sh

# 6. Start
# Running directly allows the script to use its own shebang (#!/bin/bash)
ENTRYPOINT ["sh","/app/entrypoint.sh"]